quarkus.apicurio.registry.protobuf.index-dependencies=com.example:catalog-protobuf-model

mp.messaging.incoming.books-in.connector=smallrye-kafka
mp.messaging.incoming.books-in.topic=it-books
mp.messaging.incoming.books-in.value.deserializer=io.apicurio.registry.serde.protobuf.ProtobufKafkaDeserializer
mp.messaging.incoming.books-in.apicurio.registry.deserializer.value.return-class=com.example.catalog.Book
mp.messaging.incoming.books-in.auto.offset.reset=earliest
mp.messaging.incoming.books-in.group.id=it-books-consumer
